from app.services.cliente_service import cadastra_cliente
from app.services.produto_service import cadastra_produto
from app.services.pedido_service import cadastra_pedido
from app.services.item_pedido_service import cadastra_item_pedido
from app.services.pagamento_service import processar_pagamento