version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://fiap:fiap@db:5432/fiap
    volumes:
      - .:/app
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap
      - POSTGRES_DB=fiap
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
