version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - .:/app
      - data:/var/lib/postgresql/data
    environment:
      - DATABASE_URL